name: test if we have SECRET_TOKEN

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          [[ -z $SECRET_TOKEN ]] && Echo "I don't have SECRET_TOKEN!" && exit 1
          exit 0
